"""
instructions: settings for fjc judge data
Corey Rayburn Yung <coreyrayburnyung@gmail.com>
Copyright 2020-2021, Corey Rayburn Yung
License: Apache-2.0 (https://www.apache.org/licenses/LICENSE-2.0)
"""
import pathlib


SERVICE_URL = 'https://www.fjc.gov/sites/default/files/history/federal-judicial-service.csv'
CAREER_URL = 'https://www.fjc.gov/sites/default/files/history/professional-career.csv'
DEMOGRAPHICS_URL = 'https://www.fjc.gov/sites/default/files/history/demographics.csv'
FOLDER = '../data/judges'
SERVICE_FILE = 'fjc_service.csv'
CAREER_FILE = 'fjc_career.csv'
DEMOGRAPHICS_FILE = 'fjc_demographics.csv'
OUTPUT_FILE = 'fjc_judges.csv'
NAMES_FILE = 'fjc_names.csv'
SERVICE_PATH = pathlib.Path(FOLDER) / SERVICE_FILE
CAREER_PATH = pathlib.Path(FOLDER) / CAREER_FILE
DEMOGRAPHICS_PATH = pathlib.Path(FOLDER) / DEMOGRAPHICS_FILE
OUTPUT_PATH = pathlib.Path(FOLDER) / OUTPUT_FILE
NAMES_PATH = pathlib.Path(FOLDER) / NAMES_FILE

SERVICE_COLUMNS = ['nid', 'judge_name', 'court', 'president', 'party', 
                   'aba_rating', 'recess', 'nomination_date', 
                   'senate_vote_type', 'senate_vote', 'start_date', 
                   'senior_date', 'termination_date']
SERVICE_RENAMES = {'court_name' : 'court',
                   'appointing_president' : 'president',
                   'party_of_appointing_president' : 'party',
                   'recess_appointment_date' : 'recess', 
                   'ayes/nays' : 'senate_vote',
                   'commission_date' : 'start_date',
                   'senior_status_date' : 'senior_date'}
CAREER_COLUMNS = ['nid', 'career']
CAREER_RENAMES = {'professional_career' : 'career'}
DEMOGRAPHICS_COLUMNS = ['nid', 'last_name', 'first_name', 'middle_name', 
                        'suffix', 'birth_year', 'gender', 'race']
DEMOGRAPHICS_RENAMES = {'race_or_ethnicity' : 'race'}
ALL_COLUMNS = SERVICE_COLUMNS + CAREER_COLUMNS + DEMOGRAPHICS_COLUMNS
START_YEAR = 2000
END_YEAR = 2022

COURT_NUMBERS = {
    'Supreme Court of the United States': 99,
    'U.S. Circuit Court for the Districts of California': 9,
    'U.S. Circuit Court for the Fifth Circuit': 5,
    'U.S. Circuit Court for the First Circuit': 1,
    'U.S. Circuit Court for the Fourth Circuit': 4,
    'U.S. Circuit Court for the Second Circuit': 2,
    'U.S. Circuit Court for the Sixth Circuit': 6,
    'U.S. Circuit Court for the Third Circuit': 3,
    'U.S. Circuit Courts for the Eighth Circuit': 8,
    'U.S. Circuit Courts for the Fifth Circuit': 5,
    'U.S. Circuit Courts for the First Circuit': 1,
    'U.S. Circuit Courts for the Fourth Circuit': 4,
    'U.S. Circuit Courts for the Ninth Circuit': 9,
    'U.S. Circuit Courts for the Second Circuit': 2,
    'U.S. Circuit Courts for the Seventh Circuit': 7,
    'U.S. Circuit Courts for the Sixth Circuit': 6,
    'U.S. Circuit Courts for the Third Circuit': 3,
    'U.S. Court of Appeals for the District of Columbia Circuit': 12,
    'U.S. Court of Appeals for the Eighth Circuit': 8,
    'U.S. Court of Appeals for the Eleventh Circuit': 11,
    'U.S. Court of Appeals for the Federal Circuit': 13,
    'U.S. Court of Appeals for the Fifth Circuit': 5,
    'U.S. Court of Appeals for the First Circuit': 1,
    'U.S. Court of Appeals for the Fourth Circuit': 4,
    'U.S. Court of Appeals for the Ninth Circuit': 9,
    'U.S. Court of Appeals for the Second Circuit': 2,
    'U.S. Court of Appeals for the Seventh Circuit': 7,
    'U.S. Court of Appeals for the Sixth Circuit': 6,
    'U.S. Court of Appeals for the Tenth Circuit': 10,
    'U.S. Court of Appeals for the Third Circuit': 3,
    'U.S. Court of Customs and Patent Appeals': 13,
    'U.S. Court of Customs Appeals (later U.S. Court of Customs and Patent Appeals)': 13,
    'U.S. Court of International Trade': 101,
    'U.S. Customs Court': 102,
    'U.S. District Court for the Albemarle, Cape Fear & Pamptico Districts of North Carolina': 1001,
    'U.S. District Court for the Central District of California': 1002,
    'U.S. District Court for the Central District of Illinois': 1003,
    'U.S. District Court for the District of Alabama': 1004,
    'U.S. District Court for the District of Alaska': 1005,
    'U.S. District Court for the District of Arizona': 1006,
    'U.S. District Court for the District of Arkansas': 1007,
    'U.S. District Court for the District of California': 1008,
    'U.S. District Court for the District of Colorado': 1009,
    'U.S. District Court for the District of Columbia': 1010,
    'U.S. District Court for the District of Columbia (Supreme Court of the District of Columbia)': 1011,
    'U.S. District Court for the District of Connecticut': 1012,
    'U.S. District Court for the District of Delaware': 1013,
    'U.S. District Court for the District of Florida': 1014,
    'U.S. District Court for the District of Georgia': 1015,
    'U.S. District Court for the District of Hawaii': 1016,
    'U.S. District Court for the District of Idaho': 1017,
    'U.S. District Court for the District of Illinois': 1018,
    'U.S. District Court for the District of Indiana': 1019,
    'U.S. District Court for the District of Iowa': 1020,
    'U.S. District Court for the District of Kansas': 1021,
    'U.S. District Court for the District of Kentucky': 1022,
    'U.S. District Court for the District of Louisiana': 1023,
    'U.S. District Court for the District of Maine': 1024,
    'U.S. District Court for the District of Maryland': 1025,
    'U.S. District Court for the District of Massachusetts': 1026,
    'U.S. District Court for the District of Michigan': 1027,
    'U.S. District Court for the District of Minnesota': 1028,
    'U.S. District Court for the District of Mississippi': 1029,
    'U.S. District Court for the District of Missouri': 1030,
    'U.S. District Court for the District of Montana': 1031,
    'U.S. District Court for the District of Nebraska': 1032,
    'U.S. District Court for the District of Nevada': 1033,
    'U.S. District Court for the District of New Hampshire': 1034,
    'U.S. District Court for the District of New Jersey': 1035,
    'U.S. District Court for the District of New Mexico': 1036,
    'U.S. District Court for the District of New York': 1037,
    'U.S. District Court for the District of North Carolina': 1038,
    'U.S. District Court for the District of North Dakota': 1039,
    'U.S. District Court for the District of Ohio': 1040,
    'U.S. District Court for the District of Oregon': 1041,
    'U.S. District Court for the District of Orleans': 1042,
    'U.S. District Court for the District of Pennsylvania': 1043,
    'U.S. District Court for the District of Puerto Rico': 1044,
    'U.S. District Court for the District of Rhode Island': 1045,
    'U.S. District Court for the District of South Carolina': 1046,
    'U.S. District Court for the District of South Dakota': 1047,
    'U.S. District Court for the District of Tennessee': 1048,
    'U.S. District Court for the District of Texas': 1049,
    'U.S. District Court for the District of Utah': 1050,
    'U.S. District Court for the District of Vermont': 1051,
    'U.S. District Court for the District of Virginia': 1052,
    'U.S. District Court for the District of Washington': 1053,
    'U.S. District Court for the District of West Virginia': 1054,
    'U.S. District Court for the District of Wisconsin': 1055,
    'U.S. District Court for the District of Wyoming': 1056,
    'U.S. District Court for the Eastern District of Arkansas': 1057,
    'U.S. District Court for the Eastern District of California': 1058,
    'U.S. District Court for the Eastern District of Illinois': 1059,
    'U.S. District Court for the Eastern District of Kentucky': 1060,
    'U.S. District Court for the Eastern District of Louisiana': 1061,
    'U.S. District Court for the Eastern District of Michigan': 1062,
    'U.S. District Court for the Eastern District of Missouri': 1063,
    'U.S. District Court for the Eastern District of New Jersey': 1064,
    'U.S. District Court for the Eastern District of New York': 1065,
    'U.S. District Court for the Eastern District of North Carolina': 1066,
    'U.S. District Court for the Eastern District of Oklahoma': 1067,
    'U.S. District Court for the Eastern District of Pennsylvania': 1068,
    'U.S. District Court for the Eastern District of South Carolina': 1069,
    'U.S. District Court for the Eastern District of Tennessee': 1070,
    'U.S. District Court for the Eastern District of Texas': 1071,
    'U.S. District Court for the Eastern District of Virginia': 1072,
    'U.S. District Court for the Eastern District of Washington': 1073,
    'U.S. District Court for the Eastern District of Wisconsin': 1074,
    'U.S. District Court for the Edenton, New Bern & Wilmington Districts of North Carolina': 1075,
    'U.S. District Court for the Middle District of Alabama': 1076,
    'U.S. District Court for the Middle District of Florida': 1077,
    'U.S. District Court for the Middle District of Georgia': 1078,
    'U.S. District Court for the Middle District of Louisiana': 1079,
    'U.S. District Court for the Middle District of North Carolina': 1080,
    'U.S. District Court for the Middle District of Pennsylvania': 1081,
    'U.S. District Court for the Middle District of Tennessee': 1082,
    'U.S. District Court for the Northern District of Alabama': 1083,
    'U.S. District Court for the Northern District of California': 1084,
    'U.S. District Court for the Northern District of Florida': 1085,
    'U.S. District Court for the Northern District of Georgia': 1086,
    'U.S. District Court for the Northern District of Illinois': 1087,
    'U.S. District Court for the Northern District of Indiana': 1088,
    'U.S. District Court for the Northern District of Iowa': 1089,
    'U.S. District Court for the Northern District of Mississippi': 1090,
    'U.S. District Court for the Northern District of New York': 1091,
    'U.S. District Court for the Northern District of Ohio': 1092,
    'U.S. District Court for the Northern District of Oklahoma': 1093,
    'U.S. District Court for the Northern District of Texas': 1094,
    'U.S. District Court for the Northern District of West Virginia': 1095,
    'U.S. District Court for the Southern District of Alabama': 1096,
    'U.S. District Court for the Southern District of California': 1097,
    'U.S. District Court for the Southern District of Florida': 1098,
    'U.S. District Court for the Southern District of Georgia': 1099,
    'U.S. District Court for the Southern District of Illinois': 1100,
    'U.S. District Court for the Southern District of Indiana': 1101,
    'U.S. District Court for the Southern District of Iowa': 1102,
    'U.S. District Court for the Southern District of Mississippi': 1103,
    'U.S. District Court for the Southern District of New York': 1104,
    'U.S. District Court for the Southern District of Ohio': 1105,
    'U.S. District Court for the Southern District of Texas': 1106,
    'U.S. District Court for the Southern District of West Virginia': 1107,
    'U.S. District Court for the Western District of Arkansas': 1108,
    'U.S. District Court for the Western District of Kentucky': 1109,
    'U.S. District Court for the Western District of Louisiana': 1110,
    'U.S. District Court for the Western District of Michigan': 1111,
    'U.S. District Court for the Western District of Missouri': 1112,
    'U.S. District Court for the Western District of New Jersey': 1113,
    'U.S. District Court for the Western District of New York': 1114,
    'U.S. District Court for the Western District of North Carolina': 1115,
    'U.S. District Court for the Western District of Oklahoma': 1116,
    'U.S. District Court for the Western District of Pennsylvania': 1117,
    'U.S. District Court for the Western District of South Carolina': 1118,
    'U.S. District Court for the Western District of Tennessee': 1119,
    'U.S. District Court for the Western District of Texas': 1120,
    'U.S. District Court for the Western District of Virginia': 1121,
    'U.S. District Court for the Western District of Washington': 1122,
    'U.S. District Court for the Western District of Wisconsin': 1123,
    'Circuit Court of the District of Columbia': 103,
    'Court of Claims': 104}

CIRCUIT_NUMBERS = {
    'Supreme Court of the United States': 99,
    'U.S. Circuit Court for the Districts of California': 9,
    'U.S. Circuit Court for the Fifth Circuit': 5,
    'U.S. Circuit Court for the First Circuit': 1,
    'U.S. Circuit Court for the Fourth Circuit': 4,
    'U.S. Circuit Court for the Second Circuit': 2,
    'U.S. Circuit Court for the Sixth Circuit': 6,
    'U.S. Circuit Court for the Third Circuit': 3,
    'U.S. Circuit Courts for the Eighth Circuit': 8,
    'U.S. Circuit Courts for the Fifth Circuit': 5,
    'U.S. Circuit Courts for the First Circuit': 1,
    'U.S. Circuit Courts for the Fourth Circuit': 4,
    'U.S. Circuit Courts for the Ninth Circuit': 9,
    'U.S. Circuit Courts for the Second Circuit': 2,
    'U.S. Circuit Courts for the Seventh Circuit': 7,
    'U.S. Circuit Courts for the Sixth Circuit': 6,
    'U.S. Circuit Courts for the Third Circuit': 3,
    'U.S. Court of Appeals for the District of Columbia Circuit': 12,
    'U.S. Court of Appeals for the Eighth Circuit': 8,
    'U.S. Court of Appeals for the Eleventh Circuit': 11,
    'U.S. Court of Appeals for the Federal Circuit': 13,
    'U.S. Court of Appeals for the Fifth Circuit': 5,
    'U.S. Court of Appeals for the First Circuit': 1,
    'U.S. Court of Appeals for the Fourth Circuit': 4,
    'U.S. Court of Appeals for the Ninth Circuit': 9,
    'U.S. Court of Appeals for the Second Circuit': 2,
    'U.S. Court of Appeals for the Seventh Circuit': 7,
    'U.S. Court of Appeals for the Sixth Circuit': 6,
    'U.S. Court of Appeals for the Tenth Circuit': 10,
    'U.S. Court of Appeals for the Third Circuit': 3,
    'U.S. Court of Customs and Patent Appeals': 13,
    'U.S. Court of Customs Appeals (later U.S. Court of Customs and Patent Appeals)': 13,
    'U.S. Court of International Trade': 2,
    'U.S. Customs Court': 99999,
    'U.S. District Court for the Albemarle, Cape Fear & Pamptico Districts of North Carolina': 4,
    'U.S. District Court for the Central District of California': 9,
    'U.S. District Court for the Central District of Illinois': 7,
    'U.S. District Court for the District of Alabama': 11,
    'U.S. District Court for the District of Alaska': 9,
    'U.S. District Court for the District of Arizona': 9,
    'U.S. District Court for the District of Arkansas': 8,
    'U.S. District Court for the District of California': 9,
    'U.S. District Court for the District of Colorado': 10,
    'U.S. District Court for the District of Columbia': 12,
    'U.S. District Court for the District of Columbia (Supreme Court of the District of Columbia)': 12,
    'U.S. District Court for the District of Connecticut': 2,
    'U.S. District Court for the District of Delaware': 3,
    'U.S. District Court for the District of Florida': 11,
    'U.S. District Court for the District of Georgia': 11,
    'U.S. District Court for the District of Hawaii': 9,
    'U.S. District Court for the District of Idaho': 9,
    'U.S. District Court for the District of Illinois': 7,
    'U.S. District Court for the District of Indiana': 7,
    'U.S. District Court for the District of Iowa': 8,
    'U.S. District Court for the District of Kansas': 10,
    'U.S. District Court for the District of Kentucky': 6,
    'U.S. District Court for the District of Louisiana': 5,
    'U.S. District Court for the District of Maine': 1,
    'U.S. District Court for the District of Maryland': 4,
    'U.S. District Court for the District of Massachusetts': 1,
    'U.S. District Court for the District of Michigan': 6,
    'U.S. District Court for the District of Minnesota': 8,
    'U.S. District Court for the District of Mississippi': 5,
    'U.S. District Court for the District of Missouri': 8,
    'U.S. District Court for the District of Montana': 9,
    'U.S. District Court for the District of Nebraska': 8,
    'U.S. District Court for the District of Nevada': 9,
    'U.S. District Court for the District of New Hampshire': 1,
    'U.S. District Court for the District of New Jersey': 3,
    'U.S. District Court for the District of New Mexico': 10,
    'U.S. District Court for the District of New York': 2,
    'U.S. District Court for the District of North Carolina': 4,
    'U.S. District Court for the District of North Dakota': 8,
    'U.S. District Court for the District of Ohio': 6,
    'U.S. District Court for the District of Oregon': 9,
    'U.S. District Court for the District of Orleans': 5,
    'U.S. District Court for the District of Pennsylvania': 3,
    'U.S. District Court for the District of Puerto Rico': 1,
    'U.S. District Court for the District of Rhode Island': 1,
    'U.S. District Court for the District of South Carolina': 4,
    'U.S. District Court for the District of South Dakota': 8,
    'U.S. District Court for the District of Tennessee': 6,
    'U.S. District Court for the District of Texas': 5,
    'U.S. District Court for the District of Utah': 10,
    'U.S. District Court for the District of Vermont': 1,
    'U.S. District Court for the District of Virginia': 4,
    'U.S. District Court for the District of Washington': 9,
    'U.S. District Court for the District of West Virginia': 4,
    'U.S. District Court for the District of Wisconsin': 7,
    'U.S. District Court for the District of Wyoming': 10,
    'U.S. District Court for the Eastern District of Arkansas': 8,
    'U.S. District Court for the Eastern District of California': 9,
    'U.S. District Court for the Eastern District of Illinois': 7,
    'U.S. District Court for the Eastern District of Kentucky': 6,
    'U.S. District Court for the Eastern District of Louisiana': 5,
    'U.S. District Court for the Eastern District of Michigan': 6,
    'U.S. District Court for the Eastern District of Missouri': 8,
    'U.S. District Court for the Eastern District of New Jersey': 3,
    'U.S. District Court for the Eastern District of New York': 2,
    'U.S. District Court for the Eastern District of North Carolina': 4,
    'U.S. District Court for the Eastern District of Oklahoma': 10,
    'U.S. District Court for the Eastern District of Pennsylvania': 3,
    'U.S. District Court for the Eastern District of South Carolina': 4,
    'U.S. District Court for the Eastern District of Tennessee': 6,
    'U.S. District Court for the Eastern District of Texas': 5,
    'U.S. District Court for the Eastern District of Virginia': 4,
    'U.S. District Court for the Eastern District of Washington': 9,
    'U.S. District Court for the Eastern District of Wisconsin': 7,
    'U.S. District Court for the Edenton, New Bern & Wilmington Districts of North Carolina': 3,
    'U.S. District Court for the Middle District of Alabama': 11,
    'U.S. District Court for the Middle District of Florida': 11,
    'U.S. District Court for the Middle District of Georgia': 11,
    'U.S. District Court for the Middle District of Louisiana': 5,
    'U.S. District Court for the Middle District of North Carolina': 4,
    'U.S. District Court for the Middle District of Pennsylvania': 3,
    'U.S. District Court for the Middle District of Tennessee': 6,
    'U.S. District Court for the Northern District of Alabama': 11,
    'U.S. District Court for the Northern District of California': 9,
    'U.S. District Court for the Northern District of Florida': 11,
    'U.S. District Court for the Northern District of Georgia': 11,
    'U.S. District Court for the Northern District of Illinois': 7,
    'U.S. District Court for the Northern District of Indiana': 7,
    'U.S. District Court for the Northern District of Iowa': 8,
    'U.S. District Court for the Northern District of Mississippi': 5,
    'U.S. District Court for the Northern District of New York': 2,
    'U.S. District Court for the Northern District of Ohio': 6,
    'U.S. District Court for the Northern District of Oklahoma': 10,
    'U.S. District Court for the Northern District of Texas': 5,
    'U.S. District Court for the Northern District of West Virginia': 4,
    'U.S. District Court for the Southern District of Alabama': 11,
    'U.S. District Court for the Southern District of California': 9,
    'U.S. District Court for the Southern District of Florida': 11,
    'U.S. District Court for the Southern District of Georgia': 11,
    'U.S. District Court for the Southern District of Illinois': 7,
    'U.S. District Court for the Southern District of Indiana': 7,
    'U.S. District Court for the Southern District of Iowa': 8,
    'U.S. District Court for the Southern District of Mississippi': 5,
    'U.S. District Court for the Southern District of New York': 2,
    'U.S. District Court for the Southern District of Ohio': 6,
    'U.S. District Court for the Southern District of Texas': 5,
    'U.S. District Court for the Southern District of West Virginia': 4,
    'U.S. District Court for the Western District of Arkansas': 8,
    'U.S. District Court for the Western District of Kentucky': 6,
    'U.S. District Court for the Western District of Louisiana': 5,
    'U.S. District Court for the Western District of Michigan': 6,
    'U.S. District Court for the Western District of Missouri': 8,
    'U.S. District Court for the Western District of New Jersey': 3,
    'U.S. District Court for the Western District of New York': 2,
    'U.S. District Court for the Western District of North Carolina': 4,
    'U.S. District Court for the Western District of Oklahoma': 10,
    'U.S. District Court for the Western District of Pennsylvania': 3,
    'U.S. District Court for the Western District of South Carolina': 4,
    'U.S. District Court for the Western District of Tennessee': 6,
    'U.S. District Court for the Western District of Texas': 5,
    'U.S. District Court for the Western District of Virginia': 4,
    'U.S. District Court for the Western District of Washington': 9,
    'U.S. District Court for the Western District of Wisconsin': 7,
    'Circuit Court of the District of Columbia': 12,
    'Court of Claims': 12}

PRESIDENTS = {
    'Barack Obama' : 44, 
    'Dwight D. Eisenhower' : 34,
    'Franklin D. Roosevelt' : 32, 
    'George H.W. Bush' : 41,
    'George W. Bush' : 43, 
    'Gerald Ford' : 38, 
    'Harry S Truman' : 33, 
    'Jimmy Carter' : 39,
    'John F. Kennedy' : 35, 
    'Lyndon B. Johnson' : 36, 
    'Richard M. Nixon' : 37, 
    'Ronald Reagan' : 40,
    'William J. Clinton' : 42}